version: '2'
services:
  kafka:
    container_name: kafka-container
    image: obsidiandynamics/kafka
    restart: 'no'
    ports:
      - '2181:2181'
      - '9092:9092'
    environment:
      KAFKA_LISTENERS: 'INTERNAL://:29092,EXTERNAL://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: '6000'
      KAFKA_RESTART_ATTEMPTS: '10'
      KAFKA_RESTART_DELAY: '5'
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: '0'
    networks:
      - nest

  kafdrop:
    container_name: kafka-drop-container
    image: obsidiandynamics/kafdrop
    restart: 'no'
    ports:
      - '9000:9000'
    environment:
      KAFKA_BROKERCONNECT: 'kafka-container:29092'
    networks:
      - nest

  elasticsearch:
    container_name: elastic-search-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - ELASTIC_PASSWORD=P@ssw0rd
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - nest

  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search-container:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=P@ssw0rd
    ports:
      - 5000:5601
    networks:
      - nest

  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=GARAM
      - MONGO_INITDB_ROOT_PASSWORD=4444
    networks:
      - nest
networks:
  nest:
    driver: bridge
